### ISSUE TITLE
search order API

### ISSUE THREAD

**Issue by wmcu** [Lan-Yang/WeDeliver#3]
需要增加： 按 User ID，status 查询。
其中，status字段是一个逗号分隔的字符串，例如：

```
"F" // select status="F"
"O, D, C" // select status = "O" or status = "D" or status ="C“
```

都是正确的格式。逗号表示“或”。
这是为了在查询当前用户的Ongoing, finished订单所用。

**Comment by krist-jin** [comment]
返回的是order，还是orderrecord和order一起join的结果？

**Comment by wmcu** [comment]
Join一起的结果。

**Comment by wmcu** [comment]
Done
