### ISSUE TITLE
API: POST /v1/orderRecord, primary_key_duplicate

### ISSUE THREAD

**Issue by wmcu** [Lan-Yang/WeDeliver#6]
When primary_key_duplicate exception happens, modify matching record.
Now trigger 500 error.

**Comment by krist-jin** [comment]
modify matching record是什么意思？

**Comment by wmcu** [comment]
就是说我需要能修改已存在的记录。输入是Primarykey和其他一些field的值。

**Comment by krist-jin** [comment]
我还是没太明白。比如你insert一条新的order，新order的oid已经在order表里存在了。这样的话当然是要拒绝你这条insert。你的意思是在这种情况下更改order表里面那条记录？这样的用update不行吗？
还是说需要实现update order的接口？

**Comment by wmcu** [comment]
是要实现update的接口，我上面表达不清楚哈。
